## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_VCN-Non-Production_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:31:20.634Z"
  }
  display_name = "VCN-Non-Production"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_view export_VCN-Production_1 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:30:21.920Z"
  }
  display_name = "VCN-Production"
  freeform_tags = {
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_VCN-Non-Production_2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:31:20.634Z"
  }
  display_name = "VCN-Non-Production"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc1.iad.amaaaaaadfekhvaav33ab75iv56nd5owpw3pjqjutcsoa5pcyvxdojko3jsa"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_VCN-Production_2 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:30:21.920Z"
  }
  display_name = "VCN-Production"
  freeform_tags = {
  }
  resolver_id = "ocid1.dnsresolver.oc1.iad.amaaaaaadfekhvaa6jhs7p63yuudb5lvrfngqp74dbjwr5bjsh7n6f5tafda"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_zone export_snbastion-vcnproduction-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T16:08:30.838Z"
  }
  freeform_tags = {
  }
  name      = "snbastion.vcnproduction.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snapp-vcnproduction-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T16:07:51.366Z"
  }
  freeform_tags = {
  }
  name      = "snapp.vcnproduction.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snbackup-vcnproduction-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T16:07:08.311Z"
  }
  freeform_tags = {
  }
  name      = "snbackup.vcnproduction.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snclient-vcnproduction-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T16:06:22.333Z"
  }
  freeform_tags = {
  }
  name      = "snclient.vcnproduction.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snbackup-vcnnonproductio-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T16:04:29.557Z"
  }
  freeform_tags = {
  }
  name      = "snbackup.vcnnonproductio.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Non-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snbastion-vcnnonproductio-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:41:12.054Z"
  }
  freeform_tags = {
  }
  name      = "snbastion.vcnnonproductio.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Non-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snapp-vcnnonproductio-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:39:49.540Z"
  }
  freeform_tags = {
  }
  name      = "snapp.vcnnonproductio.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Non-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_snclient-vcnnonproductio-oraclevcn-com {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:38:34.713Z"
  }
  freeform_tags = {
  }
  name      = "snclient.vcnnonproductio.oraclevcn.com"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Non-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_4-56-10-in-addr-arpa {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:31:20.634Z"
  }
  freeform_tags = {
  }
  name      = "4.56.10.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Non-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_zone export_5-56-10-in-addr-arpa {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "oracleidentitycloudservice/jeffrey.vargas@oracle.com"
    "Oracle-Tags.CreatedOn" = "2022-12-16T15:30:21.920Z"
  }
  freeform_tags = {
  }
  name      = "5.56.10.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_VCN-Production_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_rrset export_snbastion-vcnproduction-oraclevcn-com_snbastion-vcnproduction-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbastion.vcnproduction.oraclevcn.com"
  items {
    domain = "snbastion.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbastion-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snbastion-vcnproduction-oraclevcn-com_snbastion-vcnproduction-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbastion.vcnproduction.oraclevcn.com"
  items {
    domain = "snbastion.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbastion-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snapp-vcnproduction-oraclevcn-com_snapp-vcnproduction-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snapp.vcnproduction.oraclevcn.com"
  items {
    domain = "snapp.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snapp-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snapp-vcnproduction-oraclevcn-com_snapp-vcnproduction-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snapp.vcnproduction.oraclevcn.com"
  items {
    domain = "snapp.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snapp-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snbackup-vcnproduction-oraclevcn-com_snbackup-vcnproduction-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbackup.vcnproduction.oraclevcn.com"
  items {
    domain = "snbackup.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbackup-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snbackup-vcnproduction-oraclevcn-com_snbackup-vcnproduction-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbackup.vcnproduction.oraclevcn.com"
  items {
    domain = "snbackup.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbackup-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snclient-vcnproduction-oraclevcn-com_snclient-vcnproduction-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snclient.vcnproduction.oraclevcn.com"
  items {
    domain = "snclient.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snclient-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snclient-vcnproduction-oraclevcn-com_snclient-vcnproduction-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snclient.vcnproduction.oraclevcn.com"
  items {
    domain = "snclient.vcnproduction.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snclient-vcnproduction-oraclevcn-com.id
}

resource oci_dns_rrset export_snbackup-vcnnonproductio-oraclevcn-com_snbackup-vcnnonproductio-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbackup.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snbackup.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbackup-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snbackup-vcnnonproductio-oraclevcn-com_snbackup-vcnnonproductio-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbackup.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snbackup.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbackup-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snbastion-vcnnonproductio-oraclevcn-com_snbastion-vcnnonproductio-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbastion.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snbastion.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbastion-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snbastion-vcnnonproductio-oraclevcn-com_snbastion-vcnnonproductio-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snbastion.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snbastion.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snbastion-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snapp-vcnnonproductio-oraclevcn-com_snapp-vcnnonproductio-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snapp.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snapp.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snapp-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snapp-vcnnonproductio-oraclevcn-com_snapp-vcnnonproductio-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snapp.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snapp.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snapp-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snclient-vcnnonproductio-oraclevcn-com_snclient-vcnnonproductio-oraclevcn-com_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snclient.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snclient.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snclient-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_snclient-vcnnonproductio-oraclevcn-com_snclient-vcnnonproductio-oraclevcn-com_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "snclient.vcnnonproductio.oraclevcn.com"
  items {
    domain = "snclient.vcnnonproductio.oraclevcn.com"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_snclient-vcnnonproductio-oraclevcn-com.id
}

resource oci_dns_rrset export_4-56-10-in-addr-arpa_4-56-10-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "4.56.10.in-addr.arpa"
  items {
    domain = "4.56.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_4-56-10-in-addr-arpa.id
}

resource oci_dns_rrset export_4-56-10-in-addr-arpa_4-56-10-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "4.56.10.in-addr.arpa"
  items {
    domain = "4.56.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_4-56-10-in-addr-arpa.id
}

resource oci_dns_rrset export_5-56-10-in-addr-arpa_5-56-10-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "5.56.10.in-addr.arpa"
  items {
    domain = "5.56.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_5-56-10-in-addr-arpa.id
}

resource oci_dns_rrset export_5-56-10-in-addr-arpa_5-56-10-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "5.56.10.in-addr.arpa"
  items {
    domain = "5.56.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_5-56-10-in-addr-arpa.id
}

